name: Pre-build and push devcontainer image to registry
on: [push]
jobs: 
  pre-build-dev-container:
    runs-on: ubuntu-latest
    steps:
      - name: Set version var
        uses: actions/checkout@v3
      - run: | 
          VER=$(cat VERSION).${GITHUB_SHA:0:7}
          echo "VERSION=$VER" >> $GITHUB_ENV
          echo "$VERSION"
      - name: Login to Docker Hub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: devcontainers/ci@v0.3
        with: 
          imageName: docker.io/prestevez/r-pres2-geo-vsc
          imageTag: latest,${{ env.VERSION }}
          skipContainerUserIdUpdate: true
          push: never
