name: Pre-build and push devcontainer image
on: [push]
jobs: 
  set-variables:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - run: | 
          VER=$(cat VERSION).${GITHUB_SHA:0:7}
          echo "VERSION=$VER" >> $GITHUB_ENV
  pre-build-dev-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: devcontainers/ci@v0.3
        with: 
          imageName: docker.io/prestevez/r-pres2-geo-vsc
          imageTag: ${{ env.VERSION}}
