- name: Pre-build dev container image
  uses: devcontainers/ci@v0.3
  with:
    # Image name (including registry)
    imageName: docker.io/prestevez/r-pres2-geo-vsc
    # Image tag (defaults to latest)
    imageTag: 0.1.{{ ${GITHUB_SHA:0:7} }}
    # For non-root dev containers (i.e. where `remoteUser` is specified), the action attempts to make the container user UID and GID match those of the host user. Set this to true to skip this step (defaults to false)
    skipContainerUserIdUpdate: true
